services:
  web:
    build: .
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ROOT_PATH=/wlingo
    depends_on:
      - redis
    networks:
      - wlingo-net
  redis:
    image: "redis:alpine"
    networks:
      - wlingo-net

networks:
  wlingo-net:
    driver: bridge
